### ISSUE TITLE
get location of redirect in "get" method of LoxoneHttp class

### ISSUE THREAD

**Issue by diegoin4apps** [Smarteon/loxone-java#100]
Hello,

Is it possible to save the value returned by `connection.getHeaderField("Location")` into LoxoneHttp class when "get" method returns redirect code?

I need to be able to create a variable in that class to store the return value and be able to be queried from outside that class to get the last url to which it has successfully connected.

It is quite urgent, so I would appreciate an answer as soon as possible.

Thanks in advance.

**Comment by xzavrel** [comment]
Hi @diegoin4apps,
can you please explain your use-case in form of request-response flow? Why do you want to store the value in the class?

**Comment by jimirocks** [comment]
@diegoin4apps have you solved your problem, or is this still actual?

**Comment by diegoin4apps** [comment]
@jimirocks The problem currently persists.

I need to know the last url that it has successfully connected to (after all redirects made) to store that value in my database and to be able to use it later to connect to it through a websocket.

This is why I need to store the value returned by `connection.getHeaderField("Location")` in the class to be able to consult it from outside and store it in my database.

Another valid option would be to return the value returned by `connection.getHeaderField("Location")` from the "get" method of the LoxoneHttp class so that it can be captured and stored later.

I hope you understand my explanation. If you need any other information, do not hesitate to ask me.

Thanks in advance.

**Comment by jimirocks** [comment]
@diegoin4apps First, sorry for missing your last message 4 days back. Thanks for explaining your use case a bit. It seems your problem is not very loxone specific, may be some plain HTTP library would serve your need better?

May be we could introduce something like `LoxoneHttp.getLastUrl()` which would return the last called location within this thread. Would it help you?

**Comment by diegoin4apps** [comment]
@jimirocks the proposal you indicate could solve my problem.

I would appreciate if you could make the change to add something like "LoxoneHttp.getLastUrl ()" which would return the last called location.

I look forward to your change as soon as possible.

Thanks in advance!
