### ISSUE TITLE
 Has anyone got the Lib to run on android?

### ISSUE THREAD

**Issue by patrick-dmxc** [Smarteon/loxone-java#102]
I tryed to implement this lib in my Android App, but stuck on several problems.

**Comment by jimirocks** [comment]
Hello, thanks for trying. Actually the library started as backend for android app, however than we shifted away not taking care. To sum up, the android compatibility would be nice, however is not the prirority right now.

If you post your specific issues, we will be happy to at least analyse and discuss what might be changed. Please post the issues as separate cases then.
