### ISSUE TITLE
onClose method on LoxoneWebsocketClient not calling "connectionClosed" or "autoRestart" when local end

### ISSUE THREAD

**Issue by diegoin4apps** [Smarteon/loxone-java#103]
Hello,

The problem is that when the "onClose" method of the "LoxoneWebsocketClient" class is called, if the closure is local, the "connectionClosed" and "autoRestart" methods are not being called as if it happens when the closure is remote.

I would need to be able to modify the method so that these methods are always called and that variable is passed to the "connectionClosed" method to control what to do based on it.

This would also run the task that tries to auto connect again when the connection to the socket is closed.

I await your response as soon as possible, since it is an urgent change for me.

Thanks in advance.

**Comment by jimirocks** [comment]
Hello,
thanks for the idea, however, this is made on purpose. When the websocket is closed on local end, it's probably library user who is closing it, so it should be his responsibility to start again or fail (or whatever he wants to do).

As for the `connectionClosed` event, we could add `LoxoneWebSocketListener.webSocketLocalClosed` method.

As for the scheduling reconnect on local websocket end close - I do believe it's a bad idea. It would lead to unstoppable application.

Please if you believe the opposite (or maybe misunderstanding), share your use case in form of code snippet to let me understand better.

**Comment by diegoin4apps** [comment]
Hello,

Thanks for your quick response.

I think it would help me if you could add the LoxoneWebSocketListener.webSocketLocalClosed method.

As I have already mentioned in the previous message, I am very urgent to be able to apply this change.
When do you think you could apply it?

Thanks!

**Comment by diegoin4apps** [comment]
Hello again,

Could I make the required changes and create a pull request?

**Comment by jimirocks** [comment]
@diegoin4apps I already prepared the change, is this what you wanted? However in the future, don't hesistate to create PR anytime straight away. It's always nice to discuss the code ;-)

**Comment by diegoin4apps** [comment]
Hello,

That solution is perfect.

Could you generate a new release that includes this change?

Thanks in advance!

**Comment by jimirocks** [comment]
Yes I will do the release once merged.

Also since this is not your first issue, looks like you build some project on top of the library? If you somehow can share the link to the app or code, we will be happy to add it to the refernces here at github. Also we can chat more on e-mail about library designs etc.

**Comment by jimirocks** [comment]
Released, should be visible in maven central in an hour or so

**Comment by diegoin4apps** [comment]
Hello, 

Release is not available in maven central yet.
Is there any problem?
