### ISSUE TITLE
TLS connection (https:// and wss://)

### ISSUE THREAD

**Issue by diegoin4apps** [Smarteon/loxone-java#106]
Hello,

I would like to know if the library supports TLS connection.

I await your response as soon as possible.

Thanks in advance!

**Comment by jimirocks** [comment]
yes it does

**Comment by diegoin4apps** [comment]
But is it possible to use a hostname instead of ip-port?

**Comment by jimirocks** [comment]
https without hostname doesn't make sense, so yes it's possible
