### ISSUE TITLE
Unable to authenticate within timeout with retry

### ISSUE THREAD

**Issue by NunoNogueira99** [Smarteon/loxone-java#142]
Hello good afternoon

Can someone help me, I'm trying to make an app to communicate with Loxone, when I run the library it's giving me this error (image), tell me how can i solve this problem.

![image](https://user-images.githubusercontent.com/58145881/144912693-f305bd42-816e-4ead-82fe-97cd23613438.png)

**Comment by jimirocks** [comment]
Hello, the problem is most probably in credentials, since it says `Unable to authenticate ...` but can also be some network problem. I can't say more from the image. So beeing you, I would double check the loxone miniserver is reachable, all the http and websocket relevant ports are not blocked and also the credentials used are correct. If you can share the snippet of the code and also the full stack trace I can try to guess better.

**Comment by NunoNogueira99** [comment]
these are the settings in loxone

![image](https://user-images.githubusercontent.com/58145881/144984987-b28df504-29f3-4172-a005-44433116651d.png)

**Comment by NunoNogueira99** [comment]
full stack trace

![image](https://user-images.githubusercontent.com/58145881/144985879-5e6a9ea9-477c-4097-94f0-11e2fa43d372.png)

**Comment by jimirocks** [comment]
Well the code looks OKish, but there still can be some connection issue - have you tried to reach the miniserver just by http? ie. using `LoxoneHttp`. Also try to use some notauthenticated endpoints like `jdev/cfg/api`. Also the library does pretty good logging using slf4j - if you bind it to your andorid logger and set the eevel on trace you should see lot of stuff and most probably also the reason of the failure.

Due to aynchronous processing of the authentication, it's not possible to reveal more from the exception.

**Comment by NunoNogueira99** [comment]
Good afternoon

I tried to run the code without being in an asynchronous function but it gives me the NetworkOnMainThreadException exception so I put the code in an asynchronous function.

Could you show me some code on how to send commands to loxone? And how to use LoxoneHttp? And how to use slf4j? please

I'm sorry to bother you but I'm starting to learn about Loxone

thanks

**Comment by jimirocks** [comment]
```java
new LoxoneHttp(new LoxoneEndpoint(address)).get(LoxoneMessageCommand.DEV_CFG_API)
```

As for slf4j, there is [slf4j-android](http://www.slf4j.org/android/) project providing binding for. To see the maximum info from the library set level for `cz.smarteon.loxone` to `TRACE`.

Generally I advise you to read the Loxone documentation referred from [README](https://github.com/Smarteon/loxone-java) of this library and also go through the library javadoc and even the source code - it's nothing very complicated.

**Comment by NunoNogueira99** [comment]
good afternoon thank you very much for your help. 

Can you help me with something else that I still haven't figured out how to do, I have the command in a string that I'm going to send, for example, "jev/sps/io/Attic/On" how can I send this type of command 

I've already been reading the documentation but I still don't understand how it's done

Tank you

**Comment by jimirocks** [comment]
Well that's very generic question, but generally such information could be found in `LoxoneApp`. However this library doesn't parse it completely - contributions are welcomed.

**Comment by jimirocks** [comment]
Does this mean your original question is resolved?

**Comment by NunoNogueira99** [comment]
Yes it is

The problem is in the programming of loxone, after several tests, changes of permissions in loxone and analysis of the xml code of loxone, I found that when you create a user in LoxoneConfig 12.2 it is added an "alg" variable (which I assume is the algorithm used to encrypt the password) that makes the library unable to authenticate.

Only a few hours ago I managed to solve the problem, now I was trying to understand how to solve this problem in the library, this algorithm must have to add.

In the image, you can see the variable "alg" that I say
![image](https://user-images.githubusercontent.com/58145881/145815165-8081fcf2-1997-47f2-b6e1-c9582510fa53.png)

**Comment by jimirocks** [comment]
hmm it may be the case, they changed the algorithm somehow. I will try to investigate. In the meantime, if you have the trace log, it can definitely help to resolve the issue.

**Comment by jimirocks** [comment]
So looks like the BUG in the library - it ommits the hashing algorithm value returned by `jdev/sys/getkey2/{user}` and always uses `SHA-1` algorithm. Probably all known miniservers we have accessible use `SHA-1` so far. Please could you share the result of aforementioned command on your miniserver?

**Comment by NunoNogueira99** [comment]
![image](https://user-images.githubusercontent.com/58145881/145835198-28f61c30-743b-48ba-b470-2bb085f927bf.png)

**Comment by jimirocks** [comment]
That's interesting, so the `Alg="1"` in the config means something else 🤔 . The trace log would help - to see which step of authentiction actually fails.

**Comment by jimirocks** [comment]
Or at least describe the steps in config to reach the state you have

**Comment by NunoNogueira99** [comment]
> Isso é interessante, então o `Alg="1"`na configuração significa outra coisa🤔. O log de rastreamento ajudaria - para ver qual etapa de autenticação realmente falha.

what you intended was this right?

![image](https://user-images.githubusercontent.com/58145881/145843352-18c1b97d-bffd-4e4c-be5f-ecbbb9cc901d.png)

**Comment by jimirocks** [comment]
No the library can log a lot of useful information when you turn it on, as I already wrote:

As for slf4j, there is slf4j-android project providing binding for. To see the maximum info from the library set level for `cz.smarteon.loxone` to `TRACE`.

**Comment by jimirocks** [comment]
Well I am not and android expert, but it seems the most uptodate is to use rather [android-logback](https://github.com/tony19/logback-android)  

There is XML file, when you cat `cz.smarteon.loxone` logger to `TRACE`

**Comment by jimirocks** [comment]
Released new version 2.0.2 with fix of the user algorithm used. Could fix the issue - can you please try?

**Comment by NunoNogueira99** [comment]
Good night, sorry for only answering now, but yesterday I made the changes you mentioned in the pull requests but I couldn't test. Today I've only been able to try it now, and I tried it and it seemed to be working.
Thank you very much for the quick resolution of this little problem

**Comment by jimirocks** [comment]
OK I am glad, that it helped.
