### ISSUE TITLE
Rewrite groovy tests into kotlin

### ISSUE THREAD

**Issue by jimirocks** [Smarteon/loxone-java#162]
Preferred is Kotlin, howeve java is also acceptable.

**Comment by 9gl** [comment]
Hey @jimirocks  ,
I'm interested in contributing to this issue, so before I start working 
it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by jimirocks** [comment]
Hi @9gl also @knotekt will start working on this, which is OKish since it's not small task. The basic idea:

* prefer Kotlin + junit5 + strikt.io + mockk
* we can do it per partes - no need for big bang, let's do it one after other, even we can create several pull requests
* there are already few kotlin tests in place, so the boilerplate is there
* the finite state is to remove groovy and spockframework dependency

SIDE NOTE: I am on Vacation 12.-20.8. so in the mean time @xzavrel could be available to review
