### ISSUE TITLE
TLS connection (WSS)

### ISSUE THREAD

**Issue by diegoInforapps** [Smarteon/loxone-java#183]
Hi,

I would like to know if the library allows to connect with the miniservers using the TLS protocol through WSS.

Thanks in advance.

**Comment by jimirocks** [comment]
Yes it does, just use the right LoxoneEndpoitn parameters: https://github.com/Smarteon/loxone-java/blob/4eb27285fef646f4159dc2e42f3fad313f56d22d/src/main/java/cz/smarteon/loxone/LoxoneEndpoint.java#L58
