### ISSUE TITLE
[Documentation] How to send analog value?

### ISSUE THREAD

**Issue by xavan83** [Smarteon/loxone-java#209]
The documentation and example only mention sending pulse/on/off value to a control.
How to send other kind of value like temperature, percentage,etc.

**Comment by xavan83** [comment]
This is what I do on the Loxone side but on the java side I only see this example (EXTRACT_HUMIDITY is the name of my Loxone control):
Control ctrl = loxone.app().getControl("EXTRACT_HUMIDITY",Control.class);
loxone.sendControlOn(ctrl);

Instead of sendControlOn I am looking for a method like sendControlValue(ctrl, "60%");

**Comment by jimirocks** [comment]
Hi thanks for reaching us,
can you tell what kind of block it is in Loxone config, or possibly share the relevant part of the Loxone APP json? The library currently supports limited amount of controls. That's why there is such method you desire. This could result in extending the library or some workaround (depending on your use case)

**Comment by jimirocks** [comment]
so if I understand it well you can just leverage `LoxoneHttp.get` ? In that case I would close this issue...

**Comment by xavan83** [comment]
I already made a java program to read and put some data from my loxone server.
I am using Apache httpclient to made requests like the one I mention.
I found your lib and I want to use websocket to avoid pooling the server to check the change of some data and to push some statistic data efficiently.
I don't know what you mean by "LoxoneHttp.get"

**Comment by jimirocks** [comment]
Well in this library you can use websockets to listen and http for simple command like you need, check here: https://github.com/Smarteon/loxone-java/blob/master/src/main/java/cz/smarteon/loxone/LoxoneHttp.java#L54

also you can always make your instance of [Command](https://github.com/Smarteon/loxone-java/blob/master/src/main/java/cz/smarteon/loxone/Command.java)

However as you found the solution, closing the issue
