### ISSUE TITLE
ApiInfo problem in version 10.3.11.27

### ISSUE THREAD

**Issue by diegoin4apps** [Smarteon/loxone-java#55]
I have a problem parsing the next command:
**/jdev/cfg/api**

The error message shown is as follows: 
**com.fasterxml.jackson.databind.JsonMappingException: Can't parse api info using regex**

The problem is that this new version contains the following additional parameter: "hasEventSlots" and the regular expression used to deserialize this class does not contemplate it.

Would it be possible to update this expression to contemplate this new field?

Thanks in advance.

**Comment by jimirocks** [comment]
Please see the comment by #56 the same is valid here.

**Comment by xzavrel** [comment]
I have made a PR for the problem see https://github.com/Smarteon/loxone-java/pull/57

**Comment by jimirocks** [comment]
Resolved by #57
