### ISSUE TITLE
webSocketClosed Listener

### ISSUE THREAD

**Issue by diegoin4apps** [Smarteon/loxone-java#96]
Hello,

I would like to know if it is possible how can I get a listener for when a socket is closed.
Currently there is "webSocketOpened" in "LoxoneWebSocketListener", would it be possible to incorporate something similar for when the socket is closed?
I need to notify users in my web interface when the socket is closed, and as I see currently it is not possible to perform this action, since there is no listener for it.

Thank you in advance!

**Comment by jimirocks** [comment]
Hello,

yes adding new method to `LoxoneWebSocketListener` would make sense. But please note, that in some circumstance the library tries to reestablish the close websocket, which can lead in repeated open-close notification.

Recently we introduced more high-level class `Loxone` which intentionally doesn't provide such low level websocket touching. So might be also useful to find out whether your use case cannot be better served by this class (with possible extension)?

Generally, we are quite busy right now, but will be happy to review your pull request - I believe it's simple change.

**Comment by diegoin4apps** [comment]
Hello,

I have created a pull request.

You can review it to check that everything is correct and integrate it in your next release.
