### ISSUE TITLE
LoxoneEndpoint without port

### ISSUE THREAD

**Issue by diegoin4apps** [Smarteon/loxone-java#98]
Hello,

I would like to know if it is possible to modify the "LoxoneEndpoint" class to allow connections (both via websocket and HTTP) with miniservers without port. This way connections can be made using dynamic DNS.

It would be to modify the class and the methods "webSocketUri" and "httpUrl" so that if "port" is not available, this variable is not used.

Thanks in advance.

**Comment by jimirocks** [comment]
Hello,

First, sorry for late answer due to vacation period.

Second, I don't really get your intention. In the TCP communication there is always some port - not setting it only means to use the default one (usually chosen by http or websocket library). So what would be the difference after implementing this proposal?

AFAIK the port has nothing to do with (not only) dynamic DNS. DNS only resolves the name to the IP address, then still the port must be specified to establish the connection.

Additionally, the library is proven to work connecting to loxone miniserver using loxone's DNS.

If you think I am wrong, please provide some example proving it. Thanks

**Comment by diegoin4apps** [comment]
Hello,

You're right and you always have to use a port in TCP connections.

The problem is that I need to connect to a url like the following:
dns.loxonecloud.com:80**/EEE00074006E**
address:port/folder

Right now the constructors of the class "LoxoneEndpoint" only allow registering the address and the port, but I would need to be able to register a third parameter and modify the "webSocketUri" and "httpUrl" methods so that they would use this new parameter if it was defined.

**Comment by jimirocks** [comment]
Ahh, so what you actually want is to set the path prefix (folder) - this would be possible, but not very simple change.

However, as far as I know the loxone's DNS works, the `EEE00074006E.dns.loxonecloud.com:80` should work well - please test whether it's sufficient for you.

**Comment by diegoin4apps** [comment]
Hello again,

Your answer is correct. EEE00074006E.dns.loxonecloud.com:80 correctly redirects to the defined ip and port.

The problem is that when an http request is made using the "get" method of the "LoxoneHttp" class it returns the code 307.

As I can see in the code of this class, this redirect error code is not covered (instead, code 301 "HTTP_MOVED_PERM" and code 302 "HTTP_MOVED_TEMP" are covered).

I would like to know if it is possible to modify this method so that it takes into account the 307 code, and make the corresponding redirection to the location returned in the request header.

Thanks in advance.

**Comment by diegoin4apps** [comment]
Hello again,

Could you tell me if it is possible to make the change that I mentioned in the previous message?

I'm a little urged to be able to make this change.

Thank you very much

**Comment by PetrZufan** [comment]
Hey,

Yes, this change is possible. As you mentioned, it is just a modification of the `LoxoneHttp` class. 
Please make a change you need and create a pull request. We will review it.

**Comment by diegoin4apps** [comment]
Hello,

I create a pull request with the change.

Thanks!

**Comment by PetrZufan** [comment]
Nice. Just a small codestyle issue. Fix it and I'am ready to merge.

**Comment by jimirocks** [comment]
@diegoin4apps thanks for contribution and one more sorry for a bit slow reactions due to vacation period. The 0.9.1 version with your changes is now released to maven central.
